version: "3"
services:
  node-app:
    build: ./server
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./client/build:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - node-app
